spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test
    username: root
    password: aaaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost